---
version: "3.8"
services:
  bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
    deploy:
      restart_policy:
        condition: "unless-stopped"
