---
version: "3.8"
services:
  bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      CLIENT_ID: "${CLIENT_ID}"
      LOG_LEVEL: "${LOG_LEVEL}"
      TEST_SERVERS: "${TEST_SERVERS}"
      SENTENCE_CSV_FILE: "${SENTENCE_CSV_FILE}"
    deploy:
      restart_policy:
        condition: "unless-stopped"
